#!/bin/bash
echo 'Top 10 memory usage processes'
#ps aux --sort=vsz,-rss | head -10
ps aux | awk '{mem[$11]+=int($6/1024)}; {cpuper[$11]+=$3};{memper[$11]+=$4}; END {for (i in mem) {print cpuper[i]"% ",memper[i]"% ",mem[i]" MB ",i}}' | sort -k3nr | head -n 10
free -m